version: '3'
services:
 
  keras:
    container_name: keras
    build:
      context: keras
    image: keras
    env_file: ./keras/keras.env
    environment:
      WAIT_HOSTS: mysql:3306
    ports:
      - "5001:5001"
    devices:
      - "/dev/nvidia0:/dev/nvidia0"
      - "/dev/nvidiactl:/dev/nvidiactl"
      - "/dev/nvidia-modeset:/dev/nvidia-modeset"
      - "/dev/nvidia-uvm:/dev/nvidia-uvm"
      - "/dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools"
    volumes:
      - /usr/lib/x86_64-linux-gnu/libcuda.so:/usr/lib/x86_64-linux-gnu/libcuda.so:ro
      - /usr/lib/x86_64-linux-gnu/libcuda.so.1:/usr/lib/x86_64-linux-gnu/libcuda.so.1:ro
      - /usr/lib/x86_64-linux-gnu/libcuda.so.430.50:/usr/lib/x86_64-linux-gnu/libcuda.so.430.50:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-cbl.so.430.50:/usr/lib/x86_64-linux-gnu/libnvidia-cbl.so.430.50:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-cfg.so:/usr/lib/x86_64-linux-gnu/libnvidia-cfg.so:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.1:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.430.50:/usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.430.50:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-compiler.so.430.50:/usr/lib/x86_64-linux-gnu/libnvidia-compiler.so.430.50:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-container.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-container.so.1:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-container.so.1.0.5:/usr/lib/x86_64-linux-gnu/libnvidia-container.so.1.0.5:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-eglcore.so.430.50:/usr/lib/x86_64-linux-gnu/libnvidia-eglcore.so.430.50:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-encode.so:/usr/lib/x86_64-linux-gnu/libnvidia-encode.so:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-encode.so.1:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.430.50:/usr/lib/x86_64-linux-gnu/libnvidia-encode.so.430.50:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.430.50:/usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.430.50:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-fbc.so:/usr/lib/x86_64-linux-gnu/libnvidia-fbc.so:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-fbc.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-fbc.so.1:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-fbc.so.430.50:/usr/lib/x86_64-linux-gnu/libnvidia-fbc.so.430.50:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.430.50:/usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.430.50:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-glsi.so.430.50:/usr/lib/x86_64-linux-gnu/libnvidia-glsi.so.430.50:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-glvkspirv.so.430.50:/usr/lib/x86_64-linux-gnu/libnvidia-glvkspirv.so.430.50:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-ifr.so:/usr/lib/x86_64-linux-gnu/libnvidia-ifr.so:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-ifr.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-ifr.so.1:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-ifr.so.430.50:/usr/lib/x86_64-linux-gnu/libnvidia-ifr.so.430.50:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-ml.so:/usr/lib/x86_64-linux-gnu/libnvidia-ml.so:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.430.50:/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.430.50:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.1:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.430.50:/usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.430.50:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-opticalflow.so:/usr/lib/x86_64-linux-gnu/libnvidia-opticalflow.so:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-opticalflow.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-opticalflow.so.1:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-opticalflow.so.430.50:/usr/lib/x86_64-linux-gnu/libnvidia-opticalflow.so.430.50:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so:/usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.1:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.430.50:/usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.430.50:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-rtcore.so.430.50:/usr/lib/x86_64-linux-gnu/libnvidia-rtcore.so.430.50:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-tls.so.430.50:/usr/lib/x86_64-linux-gnu/libnvidia-tls.so.430.50:ro
      - "./ftp/data:/srv/files"

  mysql:
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "mydb"
    image: "mysql/mysql-server:8.0.18"
    depends_on:
      - ftpd_server
    ports:
      - "3306:3306"
    volumes:
      - "db-data-park:/var/lib/mysql"
      - "./db/tables.sql:/docker-entrypoint-initdb.d/tables.sql"

  ftpd_server:
    image: stilliard/pure-ftpd:hardened
    container_name: ftp
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - "./ftp/data:/home/username/"
      - "./ftp/passwd:/etc/pure-ftpd/passwd"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: username
      FTP_USER_PASS: mypass
      FTP_USER_HOME: /home/username
    restart: always

  angular:
      container_name: angularcontainer
      build: ./web
      volumes:
        - './web:/usr/src/app' 
      ports: 
        - '4200:4200'
      command: > 
        bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"

volumes:
  db-data-park:
  files:
