version: '3'
services:
 
  keras:
    container_name: keras
    build:
      context: keras
    image: keras
    env_file: ./keras/keras.env
    depends_on:
      - tesseract

  tesseract:
    container_name: tesseract
    build: 
      context: ocr-tesseract
    image: tesseract
    ports:
      - "5000:5000"

  